name = input("Enter your first name: ")
verb = input("Enter verb in past tense: ")
subject = input("Enter a school subject: ")
noun1 = input("Enter a noun: ")
adj1 = input("Enter adjective: ")
color1 = input("Enter color: ")
face = input("Enter facial feature: ")
song = input("Name of song: ")
adj2 = input("Enter adjective: ")
noun2 = input("Enter a noun: ")
holiday = input("Enter a holiday: ")
number = input("Enter a number: ")
noun3 = input("Enter a noun: ")
color2 = input("Enter color: ")
noun4 = input("Enter a noun: ")
plural = input("Enter a plural noun: ")

print("Dear %s," % name.capitalize())
print("I still remember the first time I %s eyes on you. It was during %s class, and you came in to give our teacher a %s. The very first thing I noticed was your %s face, and your large %s %s. I even heard %s playing in background! Since that day, I admit I have had a %s %s on you! I will reveal my secret identity on %s at %s o'clock sharp. Meet me behind the %s. I'll be wearing a %s %s." % (verb.lower(), subject.lower(), noun1.lower(), adj1.lower(), color1.lower(), face.lower(), song, adj2.lower(), noun2.lower(), holiday.capitalize(), number, noun3.lower(), color2.lower(), noun4.lower()))
print("%s and kisses, your secret admirer" % (plural.capitalize()))